name: Android CI

on:
  push:
    branches: [ "kitkat-wear" ]
  pull_request:
    branches: [ "kitkat-wear" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 7
      uses: actions/setup-java@v3
      with:
        java-version: '7'
        distribution: 'oracle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 1.10
    - name: Build
      run: gradle 
